name: flicknova
description: Netflix + Letterboxd inspired movie discovery app with cinematic design
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Core architecture
  flutter_riverpod: ^3.0.3
  freezed: ^3.2.3
  go_router: ^17.0.0
  flutter_localizations:
    sdk: flutter


  # HTTP & Caching
  dio: ^5.9.0  # Latest stable Dec 2025 â€“ battle-tested HTTP client
  dio_cache_interceptor: ^4.0.5
  pretty_dio_logger: ^1.4.0 # Beautiful colored logs with request/response/stack
  stack_trace: ^1.12.1     # Clean stack trace formatting

  # Backend & Auth
  crypto: ^3.0.7
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  supabase_flutter: ^2.12.0
  firebase_core: ^4.3.0


  # Local storage
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5


  # UI & Polish
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.2.3
  lottie: ^3.3.2
  glassmorphism: ^3.0.0
  google_fonts: ^6.2.0

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.0
  envied: ^1.3.2
  collection: ^1.18.0
  uuid: ^4.4.0
  flutter_screenutil: ^5.9.3
  another_flushbar: ^1.12.32

  # Optional Phase 2
  fl_chart: ^0.70.0
  infinite_scroll_pagination: ^4.0.0
  youtube_player_flutter: ^9.1.3
  shared_preferences: ^2.5.4
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
#
#  # Code generation
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0
  envied_generator: ^1.3.2
  rename: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/branding/
    - assets/lottie/
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/


# FLUTTER_GEN CONFIG (this is what was missing!)
flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    flutter_svg: true
    rive: true
    lottie: true